In [1]:
from trialscope.api import fetch_trials, studies_to_dataframe

studies = fetch_trials("diabetes", max_trials=200)
print(len(studies))

200

In [2]:
df = studies_to_dataframe(studies)
df.head()

,nct_id,title,status,start_date,completion_date,phase,enrollment,sponsor,sponsor_class
0,NCT03162237,Safety and Efficacy Study of Islets Xenotransp...,COMPLETED,2013-07,2018-12,NA,20.0,"Wei Wang,MD",OTHER
1,NCT01121172,Apelin Levels and G212A Polymorphism of Apelin...,COMPLETED,2010-05,2014-01,NaN,180.0,Aristotle University Of Thessaloniki,OTHER
2,NCT01630512,Mindfulness-Based Cognitive Therapy (MBCT) and...,COMPLETED,2011-05,NaN,NA,94.0,University Medical Center Groningen,OTHER
3,NCT01698112,Does Flaxseed Supplementation Improve Glycemic...,COMPLETED,2006-07,2009-06,NA,25.0,"University of Colorado, Colorado Springs",OTHER
4,NCT01221467,Closing the Loop in Youth With Type 1 Diabetes...,COMPLETED,2012-06,2013-03,PHASE2,17.0,University of Cambridge,OTHER

In [3]:
print(df.shape)
df["phase"].value_counts(dropna=False)

(200, 9)

phase
NA                82
NaN               36
PHASE4            21
PHASE1            20
PHASE2            17
PHASE3            15
EARLY_PHASE1       4
PHASE1, PHASE2     3
PHASE2, PHASE3     2
Name: count, dtype: int64

In [4]:
df.isna().sum()

nct_id              0
title               0
status              0
start_date          1
completion_date     7
phase              36
enrollment          1
sponsor             0
sponsor_class       0
dtype: int64

In [6]:
import json

# Small sample of raw API output, used later by pytest instead of the live site
with open("tests/fixtures/diabetes_sample.json", "w", encoding="utf-8") as f:
    json.dump(studies[:20], f, indent=2)

# Flattened table, so you don't re-hit the API every time
df.to_csv("data/diabetes_raw.csv", index=False)

In [8]:
df["phase"].value_counts(dropna=False)

phase
NA                82
NaN               36
PHASE4            21
PHASE1            20
PHASE2            17
PHASE3            15
EARLY_PHASE1       4
PHASE1, PHASE2     3
PHASE2, PHASE3     2
Name: count, dtype: int64

In [9]:
%load_ext autoreload
%autoreload 2

In [10]:
from trialscope.cleaning import clean_trials

clean = clean_trials(df)
clean["phase"].value_counts()

phase
Not applicable    82
Not reported      36
Phase 4           21
Phase 1           20
Phase 2           17
Phase 3           15
Early Phase 1      4
Phase 1/2          3
Phase 2/3          2
Name: count, dtype: int64

In [11]:
clean.dtypes
clean[["start_date", "start_year", "enrollment", "status"]].head()

  start_date  start_year  enrollment     status
0 2013-07-01      2013.0        20.0  Completed
1 2010-05-01      2010.0       180.0  Completed
2 2011-05-01      2011.0        94.0  Completed
3 2006-07-01      2006.0        25.0  Completed
4 2012-06-01      2012.0        17.0  Completed